### ISSUE TITLE
tmux dimmed theme - invisible inactive windows

### ISSUE THREAD

**Issue by jsec** [projekt0n/github-nvim-theme#105]
When using the dimmed tmux theme, inactive windows are near invisible.

I'll play around with this, and if I can get it fixed.

![image](https://user-images.githubusercontent.com/782969/136676450-384ef9b0-c25c-4935-a75c-d9586e1884ba.png)

**Comment by ful1e5** [comment]
Thanks, @jsec for the PR :+1:
