### ISSUE TITLE
Default statusline color

### ISSUE THREAD

**Issue by kristijanhusak** [projekt0n/github-nvim-theme#11]
Hi,

thanks for the colorscheme, looks great.

Would you consider changing the default statusline background to something that has a bit less contrast, or providing an option to change it?

This is how it looks now:
![statusline_default](https://i.imgur.com/0n0lMxQ.png)

I have custom statusline without any plugins, and currently my workaround is this:

```lua
vim.cmd[[augroup vimrc_colorscheme]]
  vim.cmd[[autocmd ColorScheme * lua kris.colorscheme.setup_github()]]
vim.cmd[[augroup END]]

function _G.kris.colorscheme.setup_github()
  local colors = require('github-theme.colors').setup()
  vim.cmd(string.format('hi StatusLine guibg=%s', colors.white))
end

require("github-theme").setup({
  themeStyle = 'light',
})
```

And now it looks like this:
![statusline_updated](https://i.imgur.com/9m5aV5r.png)

Also, i'm not able to override dark color this way, for which I'll open up a separate issue.

**Comment by ful1e5** [comment]
Now you override the statusline background color with `bg_statusline`.

```lua
require("github-theme").setup({
  colors = {bg_statusline = "#000000"}    -- set statusline background to black
})
```

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by xuxinx** [comment]
Then the color of statusline fonts should be customizable too

**Comment by ful1e5** [comment]
```lua
require("github-theme").setup({
  colors = {
    bg_statusline = "#000000", -- set statusline background to black
    fg_statusline = "#ffffff" -- set statusline foreground to white
  }
})
```

ref: af158c9
