### ISSUE TITLE
Incompatible w/ Lualine tabline

### ISSUE THREAD

**Issue by e2oneedh2o** [projekt0n/github-nvim-theme#133]
You are only able to see the the open tab when using this colorscheme with lualine's tabline. I believe that this happens when you put buffers in the tabline too.
[Imgur link of bug](https://imgur.com/a/nYibfFK)
## Lualine config
       require'lualine'.setup {
       options = {
            icons_enabled = true,
            theme = 'auto',
            component_separators = { left = '|', right = '|'},
            section_separators = { left = '', right = ''},
            disabled_filetypes = {},
            always_divide_middle = true,
        },
        sections = {
            lualine_a = {'mode'},
            lualine_b = {'branch', 'diff',
                {'diagnostics', sources={'nvim_lsp'}
                }},
            lualine_c = {'filename'},
            lualine_x = {'encoding', 'fileformat', 'filetype'},
            lualine_y = {'progress'},
            lualine_z = {'location'}
        },
        inactive_sections = {
            lualine_a = {},
            lualine_b = {},
            lualine_c = {'filename'},
            lualine_x = {'location'},
            lualine_y = {},
            lualine_z = {}
        },
        tabline = {
            lualine_a = {'tabs'},
            lualine_b = {},
            lualine_c = {},
            lualine_x = {},
            lualine_y = {},
            lualine_z = {}
        },
        extensions = {}
        },

**Comment by ful1e5** [comment]
I like to receive PR for this bug.
