### ISSUE TITLE
Readme config exemple is wrong!

### ISSUE THREAD

**Issue by gabrielDpadua21** [projekt0n/github-nvim-theme#134]
This exemplo in readme is not workin because forget the ' in object

Error

`
" Example config in VimScript
" NOTE: Configuration needs to be set BEFORE loading the color scheme with `colorscheme` command
let g:github_function_style = "italic"
let g:github_sidebars = ["qf", "vista_kind", "terminal", "packer"]

" Change the "hint" color to the "orange" color, and make the "error" color bright red
let g:github_colors = {
  \ 'hint: 'orange',
  \ 'error': '#ff0000'
\ }

" Load the colorscheme
colorscheme github_dark
`

Work
`
" Example config in VimScript
" NOTE: Configuration needs to be set BEFORE loading the color scheme with `colorscheme` command
let g:github_function_style = "italic"
let g:github_sidebars = ["qf", "vista_kind", "terminal", "packer"]

" Change the "hint" color to the "orange" color, and make the "error" color bright red
let g:github_colors = { 'hint': 'orange', 'error': '#ff0000'}

" Load the colorscheme
colorscheme github_dark
`

**Comment by ful1e5** [comment]
I can't see the difference in both configs.

**Comment by gabrielDpadua21** [comment]
Missin the ' in hint attribute in github_colors object when you run de config get a error message.

**Comment by ful1e5** [comment]
Thanks, @gabrielDpadua21
