### ISSUE TITLE
How to override Normal guibg?

### ISSUE THREAD

**Issue by nyngwang** [projekt0n/github-nvim-theme#143]
Can you update the docs?

**Comment by ful1e5** [comment]
You can change `Normal` guibg with overriding `bg` color but override **individual highlights is not possible yet**. 

#### lua 
```lua
require("github-theme").setup({
  colors = {
    bg = "#000000" -- Black
  }
})
```

#### vim
```vim
let g:github_colors = {
  \ 'bg': '#000000' " Black
\ }
```

**Comment by nyngwang** [comment]
Thank you, I found the solution after I asked. But it's a little bit time consuming guessing: `guibg`, `background`, gui_bg`, .... An little update on the documentation would be great.
