### ISSUE TITLE
EoL list character is too dark

### ISSUE THREAD

**Issue by iloverink** [projekt0n/github-nvim-theme#150]
The eol marker is too dark compared to the other list characters. It is enabled on all lines but blends in with the background when not setting cursorline
![image](https://user-images.githubusercontent.com/47754304/146600271-03998130-9c70-4f69-8ef5-f307e980f4da.png)

**Comment by ful1e5** [comment]
listchar **eol** highlight linked with `EndOfBuffer`. That means you have to disable the `hide_end_of_buffer` option to make the `eol` listchar visible.

https://user-images.githubusercontent.com/24286590/146638008-72aea9e2-f5f3-4d3c-81c3-465e3b241c15.mp4

**Comment by iloverink** [comment]
Ah Thanks!
