### ISSUE TITLE
[bug] attempt to call field 'nvim_create_augroup' (a nil value)

### ISSUE THREAD

**Issue by uolot** [projekt0n/github-nvim-theme#168]
After updating the plugin minutes ago, I'm now getting the following error:

```
E5108: Error executing lua ...nvim/plugged/github-nvim-theme/lua/github-theme/util.lua:112: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        ...nvim/plugged/github-nvim-theme/lua/github-theme/util.lua:112: in function 'autocmds'
        ...nvim/plugged/github-nvim-theme/lua/github-theme/util.lua:232: in function 'load'
        ...nvim/plugged/github-nvim-theme/lua/github-theme/init.lua:15: in function 'setup'
        [string ":lua"]:538: in main chunk
```

I'm using Plug.vim for managing my plugins, and it pulled the following commits:

```
  * 7946707 refactor: lua autocmds (47 minutes ago)
  * 715c554 BREAKING_CHANGE: set lualine theme with `theme="auto"` (4 hours ago)
  * 7ed3408 docs: LUALINE.md updated (fixed #167) (5 hours ago)
```

My neovim details:

```
$  nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

**Comment by uolot** [comment]
I can confirm now that the latest commit is the culprit here. After pinning to the previous commit with

```
Plug 'projekt0n/github-nvim-theme', { 'commit': '715c554' }
```

the error message doesn't show up anymore.

**Comment by sabitm** [comment]
neovim nightly needed for `nvim_create_augroup` to work. So either pinning to previous commit or install neovim nightly to solve the issue

**Comment by ful1e5** [comment]
I reverted 79467077ddcdfb35aff0d03985bdb0c33038d13e from upstream temporarily because It's causing more errors. Hopefully in the future, I will manage to add version checking inside `util.autocmds` function as @uolot mention. Until then, I leave this issue open.

PRs are welcome.
