### ISSUE TITLE
Error running config: 'group' must be a string with default config

### ISSUE THREAD

**Issue by tim-hilt** [projekt0n/github-nvim-theme#169]
This is the full error:

```
packer.nvim: Error running config for github-nvim-theme: ...packer/start/github-nvim-theme/lua/github-theme/util.lua:115: 'group' must be a string
```

And this is my configuration for github-nvim-theme:

``` lua
  use {
    "projekt0n/github-nvim-theme",
    config = function()
      require("github-theme").setup({})
    end
  }
  -- related:
  use {
    "nvim-lualine/lualine.nvim",
    after = "github-nvim-theme",
    requires = { "kyazdani42/nvim-web-devicons", opt = true },
    config = function()
      require("lualine").setup({ options = { theme = "auto" } })
    end
  }
```

You can take a look at the config in context [here](https://github.com/tim-hilt/nvim/blob/main/lua/tim/plugins.lua#L104-L117).

**Comment by tim-hilt** [comment]
Update: pinning to commit 4ad832edd70be94 makes the error go away, but now lualine looks funny.

**Comment by ful1e5** [comment]
Duplicate of #168

**Comment by tim-hilt** [comment]
@ful1e5 I’m using the newest Neovim-commit, so that shouldn’t be a duplicate. If you navigate to misc.lua in my config you can see, that I’m already using native augroups. The error even looks different than the one from #168. Also pinning to the commit mentioned in the linked issue didn’t solve the issue for me.

**Comment by tim-hilt** [comment]
Thank you!

**Comment by ful1e5** [comment]
Should you try with 508d430f2837bdd6aef0d86bb3092e46b3a9f8c8 ?

**Comment by tim-hilt** [comment]
I’ll check it out later today. Reverting seems to be a real pity, however holding out native aus should also benefit users, that are not using nightly Neovim.

**Comment by ful1e5** [comment]
I will manage to add native autocmds in short with `version` condition.

**Comment by tim-hilt** [comment]
That's a good approach. I checked the newest commit and it seems to work again for me, so this issue can be closed.
