### ISSUE TITLE
Light mode cursor is abnormal

### ISSUE THREAD

**Issue by askfiy** [projekt0n/github-nvim-theme#173]
as the picture shows:

![Peek 2022-03-30 18-20](https://user-images.githubusercontent.com/81478335/160809760-035819f6-f622-441b-8dd0-f8bb2044e7da.gif)

I have to style the cursor myself, but it's not a good solution.

Please fix it as soon as possible.

**Comment by ful1e5** [comment]
Cursor colors are not controlled by vim at all, but by your terminal. Check [terminal](https://github.com/projekt0n/github-nvim-theme/tree/main/terminal) directory for themes.
