### ISSUE TITLE
Cursor too dark

### ISSUE THREAD

**Issue by zbindenren** [projekt0n/github-nvim-theme#174]
Hi

Is it possible to change the cursor color to make it a little lighter? Currently it is almost not possible to read the letter under the cursor:

![Selection_006](https://user-images.githubusercontent.com/1607088/161206200-62be20dd-7c6e-49d4-9dfd-a63dd5b0f9cd.png)
![Selection_005](https://user-images.githubusercontent.com/1607088/161206267-45027551-0256-48fd-a14a-3277d3460215.png)

**Comment by ful1e5** [comment]
You can change cursor color from terminal theme.
