### ISSUE TITLE
Override color for selected variant only

### ISSUE THREAD

**Issue by JoseConseco** [projekt0n/github-nvim-theme#176]
Hi, I just noticed that when I use color override - eg
colors = {bg = "#f5f5f5"},
Then all github-nivm themes will use this white color (obviously I do not want to use white for dark themes).  It would be great if we coul override color only for selected theme. Something like
```
colors = {
   github_light = { bg=  white, comment=xyz },
   github_dark = { ... }
}
```

**Comment by ful1e5** [comment]
I have just completed a major update to the theme's codebase and added the feature you requested. With this update, you can now override colors for specific theme styles or all of them using `palettes` and `specs` configs. You can find more information about this in the changelog, which is available from revision 1a96bd061cc30ab2543461d279baf87a68857ffe onwards. To access the changelog, use the command `:h github-theme.changelog-23042023` in vim or refer to this [discussion](https://github.com/projekt0n/github-nvim-theme/discussions/198#discussioncomment-5700014).

Thank you for submitting such a great feature request. Although I plan to add more examples and details in the future, I am closing this issue as complete.
