### ISSUE TITLE
my icon color is overweitten

### ISSUE THREAD

**Issue by Damaged-Code** [projekt0n/github-nvim-theme#181]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/26178326/168018591-0eacc352-878a-4140-8e68-2e143fbbc2ba.png">

**Comment by Damaged-Code** [comment]
when i use require('github-theme').setup() to change style config it will overweitten icon color

**Comment by ful1e5** [comment]
> when i use require('github-theme').setup() to change style config it will overweitten icon color

Try to load icons after `github-nvim-theme`.

```lua
  use({
    '~/GitHub/projekt0n/github-nvim-theme',
    config = function()
      -- github theme config
    end,
  })
  use({
    'kyazdani42/nvim-web-devicons',
    after = 'github-nvim-theme'
  })
```

**Comment by Damaged-Code** [comment]
> 

I'm use vim-plugin to manage plug,so I move github theme on the  top,still not working
<img width="494" alt="image" src="https://user-images.githubusercontent.com/26178326/168083030-461cba5a-aa24-4125-a5d0-9aa9166e6a5c.png">

**Comment by mycf** [comment]
me too
