### ISSUE TITLE
Don't set foreground colour for `Diff*` groups?

### ISSUE THREAD

**Issue by tombh** [projekt0n/github-nvim-theme#182]
I just installed the [Diffview plugin](https://github.com/sindrets/diffview.nvim) and noticed that syntax highlighting was being overwritten by the `Diff*` groups. With this override I got the syntax highlighting back and tidied up the diff-changed colours:
```lua
overrides = function(c)
  return {
    DiffAdd = {
      bg = c.diff.add,
    },
    DiffChange = {},
    DiffDelete = {
      bg = c.diff.delete,
    },
    DiffText = { bg = c.diff.change },
  }
end,
```

Edit: added link to Diffview plugin

**Comment by luisdavim** [comment]
@tombh could you maybe open a PR for this?
