### ISSUE TITLE
[Feature] Bold for keyword/func_name etc?

### ISSUE THREAD

**Issue by ray-x** [projekt0n/github-nvim-theme#19]
Would be great to add bold for keyword etc.

**Comment by ful1e5** [comment]
Already supported 🙂

Check `:help highlight-args` for all options. These options are also supported with other styles like `commentStyle`, `functionStyle`, `variableStyle`. 

Refrence [README.md#configuration](https://github.com/projekt0n/github-nvim-theme#configuration) for **default** value.

```lua
require("github-theme").setup({
  keywordStyle = "bold",
})
```
