### ISSUE TITLE
How to remove blue color from status line

### ISSUE THREAD

**Issue by nappalm** [projekt0n/github-nvim-theme#195]
I use Feline, I don't like the blue color, is it possible to disable the color in the status line?

**Comment by ful1e5** [comment]
You can override `bg` color in the `Statusline` highlight.
 ```lua
require('github-theme').setup({
  -- ...
  overrides = function(c)
    return {
      Statusline = { bg = c.bg, fg = c.fg_light },
    }
  end,
  dev = true,
})
```

Check [palette module](https://github.com/projekt0n/github-nvim-theme/tree/0e0f8c3d5edfd99f8a46a03f400bfa94e540a7af/lua/github-theme/palette) for overridable colors.
