### ISSUE TITLE
Using default tildes on the nonelines

### ISSUE THREAD

**Issue by mustafaergul** [projekt0n/github-nvim-theme#196]
Is there any way to use back the "~" for the non-edited(noneline) lines with this theme? 

I have checked the option but it seems like there is no such option to bring back this feature.

Thanks.

**Comment by ful1e5** [comment]
Set hide_end_of_buffer to false (default is true).

lua:
```lua
require('github-theme').setup({
  -- ...
  hide_end_of_buffer = false,
})
```
or vimscript:
```vim
let g:github_hide_end_of_buffer=false
" ...
"  load the colorscheme
```
