### ISSUE TITLE
Error when I configure the theme : attempt to index field 'g' (a nil value)

### ISSUE THREAD

**Issue by theodugautier** [projekt0n/github-nvim-theme#199]
Hello,

When I setup the theme on neovim, I get this error :

![Capture d’écran du 2022-07-30 12-45-28](https://user-images.githubusercontent.com/16017408/181906856-75ca5aee-0393-4ac6-8e56-eff6701d167f.png)

```vim
call plug#begin()
Plug 'projekt0n/github-nvim-theme'
call plug#end()

colorscheme github_dark_default
```

I also tried to do this:

```vim
call plug#begin()
Plug 'projekt0n/github-nvim-theme'
call plug#end()

lua << EOF
  require("github-theme").setup({
    theme_style = "dark_default",
  })
EOF
```

But nothing makes it I always have the same error and of course the theme does not work.

Version :
    - neovim: 0.4.3

**Comment by ful1e5** [comment]
min req `neovim >= 0.5`

**Comment by theodugautier** [comment]
oh ok !
