### ISSUE TITLE
colors.lua: `bg` and `bg2` are swapped?

### ISSUE THREAD

**Issue by MaxVerevkin** [projekt0n/github-nvim-theme#2]
I've installed the light variant of this theme in both `kitty` and `nvim`: 
![image](https://user-images.githubusercontent.com/34583604/125063607-5a636600-e0b8-11eb-97fc-630e96efac8f.png)

However, I would expect both `kitty` and `nvim` to have the same background:
![image](https://user-images.githubusercontent.com/34583604/125063691-7535da80-e0b8-11eb-863c-ae583ee498de.png)

To achieve the desired result I had to swap `bg` and `bg2` in `colors.lua`. Is this a mistake?

**Comment by MaxVerevkin** [comment]
Since github's background is #ffffff, it must be a mistake in kitty's theme.

**Comment by threewholefish** [comment]
I see the same thing with the dark theme: the nvim background is lighter than the terminal (GNOME terminal, but I copied the colours from the kitty config).
