### ISSUE TITLE
Airline theme

### ISSUE THREAD

**Issue by threewholefish** [projekt0n/github-nvim-theme#20]
Hi!

Love the theme! I'm a vim-airline user, and I was hoping for a nice airline theme to go with this one.
I've tried onedark, since that was an inspiration for this one, but the colours aren't quite right.

Also, may I suggest that the colour for normal mode be blue? That seems to be the dominant colour from what I've seen of the theme.

Not sure if I need to raise an issue in the [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes) repo, or if here will do.

Thanks!

**Comment by wuelnerdotexe** [comment]
I am a contributor to **#hacktoberfest**, can I take care of this issue? 🙂

**Comment by diegoulloao** [comment]
what about this? never considered?

**Comment by Mickychen00** [comment]
Hi, how is it going?

**Comment by luisdavim** [comment]
@ful1e5 it  doesn't seem to be working. 

I get:

```
airline: The specified theme "github_dark" cannot be found.
```

I'm loading the plugin with:

```
Plug 'projekt0n/github-nvim-theme', { 'do': ':GithubThemeCompile' }
```

**Comment by luisdavim** [comment]
My bad, i was using the release tag version v1.0.0
