### ISSUE TITLE
Indent-blankline.nvim supported?

### ISSUE THREAD

**Issue by tjamesmac** [projekt0n/github-nvim-theme#201]
Hey I love the plugin! I've been using it for a while and have recently added `indent-blankline` to my configuration which the README says this plugin supports.

However, the blanklines and space chars that `indent-blankline` supports appear bright blue when used with this plugin. I noticed that the highlight groups used with `indent-blankline` don't appear to be in the `theme.lua` file.

I've added the following locally
```lua
IndentBlanklineChar = { fg = util.darken(c.syntax.comment, 0.2) },
IndentBlanklineSpaceChar = { fg = util.darken(c.syntax.comment, 0.2) },
IndentBlanklineSpaceCharBlankline = { fg = util.darken(c.syntax.comment, 0.2) },
IndentBlanklineContextChar = { fg = c.fg },
IndentBlanklineContextStart = { sp = c.fg, underline = true },
```

This seems to fix the blue lines but I'm not sure if i've missed something else?

Thanks :)

**Comment by luisdavim** [comment]
@tjamesmac would you consider opening a PR for this?

**Comment by TisnKu** [comment]
Hey @luisdavim , I opened a PR according to @tjamesmac 's suggestion. Could you take a look? Thanks.
