### ISSUE TITLE
LSP hover popup hard to read

### ISSUE THREAD

**Issue by TisnKu** [projekt0n/github-nvim-theme#209]
Thanks for the great theme! The background color of lsp hover is the same with buffer editor:
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/10512841/192576092-29b92262-a13d-4402-82d4-cfe69909e18e.png">

**Comment by ful1e5** [comment]
During the refactoring process, I resolved the issue but forgot to reference it. To ensure the fix is implemented, please use commit 4d5a4ce881d5d412b7f10f6b2fc7b3531a5138cc on the `main` branch or a later revision.

**Comment by TisnKu** [comment]
I just tried and it works.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/10512841/236598584-62899bce-65d9-4fd6-8ea0-058c0ed17f41.png">

But for some theme the hover is still not very obvious. So I enabled hover border as a workaround.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/10512841/236598648-474e8b92-529a-4526-a9e5-2fb898aaad5d.png">

**Comment by tmillr** [comment]
It's either the highlights, or floating window config (i.e. it might not even be configured to draw a border). I'm not familiar with lsp zero, but by default in neovim, hover and signature popups/floats use the highlight group `FloatBorder` for their borders. If that plugin is following the defaults, you can do `:verb hi FloatBorder` to see the highlight definition and visualize what colors are getting used. By using `:verb`, it should also tell you where that highlight group was last set.
