### ISSUE TITLE
Missing highlight groups for typescript?

### ISSUE THREAD

**Issue by abenz1267** [projekt0n/github-nvim-theme#210]
There seem to be certain highlight groups missing for typescript. F.e.

![Screenshot_20221005_230116](https://user-images.githubusercontent.com/7055955/194163566-604ea484-4f8f-40e7-8f09-0c0872976c11.png)

Hightlight groups for "interface", "ButtonProps" and all the types are missing. Works fine with Kanagawa.

Regards

**Comment by abenz1267** [comment]
Actually i noticed there's a highlights.scm for typescript in the repo. deleting it fixed it for me.

**Comment by ful1e5** [comment]
Closed ref to #211.
Thanks for contribution.
