### ISSUE TITLE
Feature request: options for overriding on specific filetypes? yaml looks bad

### ISSUE THREAD

**Issue by joshzcold** [projekt0n/github-nvim-theme#213]
The treesitter parser for `yaml` sticks the yaml keys at `TSField` which is white on this color scheme
https://github.com/ikatyang/tree-sitter-yaml/issues/28

![image](https://user-images.githubusercontent.com/36175703/195204444-1c479b5d-be73-4a27-a5be-b6c35945e074.png)

using the  autogroup recommended in the issue I was able to put it at the green used in github-nvim-theme which is closer to what is on the github website
```vim
  augroup github-yml-theme
      au!
      au BufEnter *.{yaml,yml} :hi TSField guifg=#3fb950
  augroup END
```
```lua
vim.api.nvim_create_autocmd("FileType", { pattern = { "yaml", "yaml.ansible" }, command = "hi TSField guifg=#3fb950" })
```
![image](https://user-images.githubusercontent.com/36175703/195204706-d1b7f7f3-87b8-4626-919a-a1e727ab2259.png)

My question is if we can get something more built in to override on filetypes to fix issues like this?

Or maybe better I can make a pull request to add this auto group to fix the color scheme for yaml for this one issue?

Which do you think would be better?

**Comment by joshzcold** [comment]
I kind of like this option if we want to put it in the wiki
```lua
require("github-theme").setup({
  theme_style = "dark_default",
  overrides = function (c)
    -- fix the look of yaml in this color scheme
    vim.api.nvim_create_autocmd("FileType", { pattern = { "yaml", "yaml.ansible" }, command = "hi TSField guifg=".. c.green })
    return{ }
  end
})
```
since `overrides` is a function then `c.green` is available

**Comment by olimorris** [comment]
Can't you apply `["@TSField.yaml"]` as an override?

**Comment by ful1e5** [comment]
Can you override the unassigned highlight by enabling `dev` mode? It's used to assign a new highlight that is not overridden by the colorscheme.

```lua
require('github-theme').setup({
  -- ...
  overrides = function(c)
    return {
      -- ...
      ['@field.yaml'] = { fg = c.red },
    }
  end,
  dev = true,
})
```

**Comment by joshzcold** [comment]
@ful1e5 that works well. Thank you 👍
