### ISSUE TITLE
Ruby syntax highlighting with tree sitter looks wrong

### ISSUE THREAD

**Issue by duduribeiro** [projekt0n/github-nvim-theme#215]
Hey folks 👋 

I'm using the color scheme with a ruby code and looks like some parts of the code are not getting highlighted when using tree sitter

See that `:name` didn't get highlighted 🤔 
![image](https://user-images.githubusercontent.com/771411/197290837-38469a95-9e25-4d63-9468-112a674bf909.png)

when not using tree sitter, it get highlighted as well
![image](https://user-images.githubusercontent.com/771411/197290882-7faf6b5e-c600-41ce-94b0-8f8a7f89a0c5.png)

I think it maybe something on the theme because using other colorscheme works

![image](https://user-images.githubusercontent.com/771411/197290934-5a0502cb-8d9d-4a1d-968a-293777ce2673.png)

any idea why this happen?

Thanks

**Comment by duduribeiro** [comment]
also it does not look like the screenshot from the example 😄 

<img width="274" alt="image" src="https://user-images.githubusercontent.com/771411/197291460-27de55ee-dc4d-47c8-8f07-50ee2d9ef1c9.png">


am I doing something wrong?

**Comment by idm1try** [comment]
problem in #214

**Comment by idm1try** [comment]
temporarily downgrade treesitter to https://github.com/nvim-treesitter/nvim-treesitter/commit/4cccb6f494eb255b32a290d37c35ca12584c74d0

**Comment by duduribeiro** [comment]
thanks so much for that @idm1try ! it worked perfectly.

The only odd is that the class name is being red instead of purple (like in the print screen from example on readme). See the print screen bellow
<img width="491" alt="image" src="https://user-images.githubusercontent.com/771411/197445829-8d05a49d-e7fc-4185-9a44-bc0aa49942c3.png">

is this the expected output?

thanks a lot

**Comment by ful1e5** [comment]
I have patched the updated tree-sitter highlight group to upstream #222, and I am closing this issue. If the issue persists, please reopen it.
