### ISSUE TITLE
LSPReference background

### ISSUE THREAD

**Issue by ray-x** [projekt0n/github-nvim-theme#22]
The LspReferenceRead/Write backround for the dark theme is 
```
hi LspReferenceRead                                                                                                                                                               
LspReferenceRead xxx guibg=#e1e4e8 
```
I would say it is very hard to read the character with #e1e4e8 as background. Is this on purpose? or #e1e4e8 is supposed to  be light colorscheme?

**Comment by ful1e5** [comment]
Check  b593976 on #21
