### ISSUE TITLE
Typescript highlighting colors seem wrong (with treesitter)

### ISSUE THREAD

**Issue by karimdjemai** [projekt0n/github-nvim-theme#220]
I am using the github dark default theme, but have the same problem for the others themes from this repo (but other themes e.g. catpuccin work fine, thats why I'm posting this here). 
The colors for typescript (.tsx file) look wrong, and differ from the vscode version of the same theme.

This is how my neovim looks: 

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/8942592/209886308-99b0aef6-4056-431f-a0fc-5ae367a7a516.png">

This is how it should look like (screenshot from vscode)

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/8942592/209886342-bd2ad21d-9349-49f2-aafd-ad0a7d3298dc.png">

Does this problem have something to do with this? 
https://github.com/projekt0n/github-nvim-theme/issues/214

I am not sure if I understand that correct but it seemed possibly related. 

Am I doing something wrong in my setup or is this a bug?

Thanks in advance!

**Comment by louwers** [comment]
Yup this colorscheme is not compatible with treesitter right now.
