### ISSUE TITLE
Some highlights broken after `dc7c6dc0a7fcba693217f907f8cd0a07e4b09448`

### ISSUE THREAD

**Issue by ldelossa** [projekt0n/github-nvim-theme#223]
After this commit:

`HEAD is now at dc7c6dc fix: clear highlights before applying theme` 

Some theming has broken across plugins. 

![screenshot-20230104-211731](https://user-images.githubusercontent.com/5642902/210686644-df85046a-9175-4850-9a69-4dfd14d0bf6a.png)
![screenshot-20230104-211659](https://user-images.githubusercontent.com/5642902/210686646-cf51d839-df48-4d99-86ed-f643eb5f4fe8.png)

Example is with Glance.nvim, but my lualine changed as well.

**Comment by ful1e5** [comment]
Closing according to 602d38a48eaada5d507ea3f0ea6cef12f0a6026d. If you still have issues, please continue the discussion or reopen this issue if needed. Thank you.
