### ISSUE TITLE
border is not required when using dark_sidebar

### ISSUE THREAD

**Issue by yamatsum** [projekt0n/github-nvim-theme#228]
There is no line on sidebar border in vscode.
(not strictly noticeable)
![CleanShot 2023-01-22 at 00 19 07@2x](https://user-images.githubusercontent.com/42740055/213873645-7c7b4ad7-e060-4611-9052-8c8957895f36.png)

border is not required when using dark_sidebar.
![CleanShot 2023-01-22 at 00 20 47@2x](https://user-images.githubusercontent.com/42740055/213873668-a4712fdb-ee13-4927-9298-f3ca43428fb7.png)

**Comment by ful1e5** [comment]
In Vim, all split windows are considered to be actual buffers. To change the color of the line between the nvim-tree and the buffer, it is necessary to assign a color to the `VertSplit` highlight. However, implementing this change will apply to all vertical split window division lines, which can negatively impact readability. Vim users typically prefer to distinguish between their buffers while splitting. On the other hand, VSCode has a separate group for assigning colors to its Explorer (file browsing sidebar).

If this request is feasible through the use of nvim autocmds, I would like to propose it as a feature request during or after a refactoring process. If any alternative solutions or workarounds are available, they would be greatly appreciated.

If you don't mind, could you please share the font used in the screenshot?

**Comment by yamatsum** [comment]
How about using `NvimTreeVertSplit`?

> If you don't mind, could you please share the font used in the screenshot?
- https://github.com/edihbrandon/RictyDiminished
- https://github.com/yamatsum/nonicons

**Comment by ful1e5** [comment]
There is no highlight feature that compares to the `NvimtreeVertSplit` offered by the nvim-tree plugin. I attempted to override the highlight, but was not successful. If we are able to successfully override this highlight, we may consider other sidebar-related plugins such as [litee.nvim](https://github.com/ldelossa/litee.nvim) and [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim), to maintain a consistent aesthetic. I believe it may be possible to achieve this through the use of autocmds, similar to the method used for [darkening sidebars](https://github.com/projekt0n/github-nvim-theme/blob/a93fc4cd3c16b91cf29a1387015e6e925c416efb/lua/github-theme/autocmds.lua#L25-L31).

Thank you for sharing the font.

**Comment by yamatsum** [comment]
@ful1e5 
I'm sorry, the name of the highlight seems to have changed
It worked well with `NvimTreeWinSeparator`

**Comment by ful1e5** [comment]
The `NvimTreeWinSeparator` highlight appears to be functioning properly, however, when the `side` option is changed to `'right'`, it no longer functions correctly. It appears to be an issue with the plugin.



https://user-images.githubusercontent.com/24286590/214258094-81798565-4193-4bd1-b398-3e41ad8c696b.mp4

**Comment by ful1e5** [comment]
Try a new revision on `main` after 4d5a4ce881d5d412b7f10f6b2fc7b3531a5138cc.
