### ISSUE TITLE
error when trying to use colortheme

### ISSUE THREAD

**Issue by ArtrenH** [projekt0n/github-nvim-theme#230]
When I try to reload neovim with the following configuration in the init.vim file after running ":PlugInstall", I get an error message that says:
`
Error detected while processing /root/.vim/plugged/github-nvim-theme/colors/github_dark.vim:
line    3:
E5105: Error while calling lua chunk: ...im/plugged/github-nvim-theme/lua/github-theme/config.lua:11: attempt to index field 'g' (a nil value)
`
This is my init.vim file:

`set number relativenumber
syntax enable
set scrolloff=7
set backspace=indent,eol,start

call plug#begin('~/.vim/plugged')

Plug 'projekt0n/github-nvim-theme', { 'tag': 'v0.0.7' }

call plug#end()

colorscheme github_*`
Does anyone have an idea, what I might do wrong?

**Comment by ful1e5** [comment]
This error is caused by the line `colorscheme github_*` which was included for illustration purposes in the README. To apply the GitHub color scheme to Neovim, you need to specify a variant from the available options listed below:

```vim
" GitHub color scheme variants
colorscheme github_dark                     " Dark theme
colorscheme github_dark_default             " High contrast dark theme
colorscheme github_dark_colorblind          " Colorblind-friendly dark theme
colorscheme github_dimmed                   " Dimmed dark theme
colorscheme github_light                    " Light theme
colorscheme github_light_default            " High contrast light theme
colorscheme github_light_colorblind         " Colorblind-friendly light theme
```

**Comment by ArtrenH** [comment]
`
set number relativenumber
syntax enable
set scrolloff=7
set backspace=indent,eol,start

call plug#begin('~/.vim/plugged')

Plug 'projekt0n/github-nvim-theme', { 'tag': 'v0.0.7' }

call plug#end()


colorscheme github_dark
`

But with this configuration I get the same error..

**Comment by ful1e5** [comment]
Which Neovim version are you using?

**Comment by ArtrenH** [comment]
Oh thank you, I was for some reason running a super outdated version (0.4). I now installed the latest version and everything is fine.
