### ISSUE TITLE
Problem with configuration options after most recent update (88d4373, on April 6)

### ISSUE THREAD

**Issue by telemachus** [projekt0n/github-nvim-theme#238]
The latest commit (88d4373) seems to have made it impossible to turn some configuration items off.

Here is my setup code:

```lua
require('github-theme').setup({
    comment_style = 'NONE',
    keyword_style = 'NONE',
    function_style = 'NONE',
    variable_style = 'NONE',
    comment_style = 'NONE',
    theme_style = 'light',
    sidebars = { 'qf', 'lf' },
    hide_end_of_buffer = false,
    hide_inactive_statusline = false,
    dark_float = true,
    dark_sidebar = true,
    transparent = true,
    overrides = function(c)
        return {
            Conceal = { fg = c.fg },
        }
    end,
})
```

On the latest commit, comments and keywords are in italics. If I check out the second-to-last commit, everything is fine again (i.e., no italics where I don't want them). I see that you deprecated vim.g.github* configuration, but I don't think that should be my problem since I was already using a Lua setup function.

Other information:

+ neovim v0.9.0-dev-1352+g0bc323850
+ macOS 12.6.4
+ iTerm2 3.4.19

I will try to take a look at the latest commit myself over the weekend. If you need any other information, please let me know.

**Comment by idr4n** [comment]
Strangely my configuration is not picked up when I open Nvim in a normal shell session (color overrides and all...). However if I open Nvim using Tmux, then it is picked up. This happened only after the recent update.

**Comment by ful1e5** [comment]
I have rewritten the `config` module in commit 0e4887c614f6a982cdffb3651cd54543c7ef4e3e. If the issue persists, please inform me.

**Comment by telemachus** [comment]
Thanks for the quick fix. Everything seems fine for me now, so I'll close this issue.
