### ISSUE TITLE
Rust highlighting colors with treesitter appear to be wrong 

### ISSUE THREAD

**Issue by koritar-aqg** [projekt0n/github-nvim-theme#256]
Hi, I installed this theme today and the colors on my Rust code seems pretty off of what it should look like.

This is how I installed and configured it using lazy.nvim:
![image](https://github.com/projekt0n/github-nvim-theme/assets/132579113/c6311db1-6d0e-4362-b812-bcb69fa60297)

Here's a screenshot of the theme on my neovim config:
![image](https://github.com/projekt0n/github-nvim-theme/assets/132579113/66b0495e-b1d0-4c9c-a14c-c7cafc2c83ec)

And here's how it should look like based on github and vscode theme:
![image](https://github.com/projekt0n/github-nvim-theme/assets/132579113/8c2d8571-b43d-4273-9118-b53f216aba16)

**Comment by AlexXi19** [comment]
+1 on this. Colors are still a bit off 😞 . This is with github dark high contrast. 
![Screenshot 2023-05-22 at 12 40 57 PM](https://github.com/projekt0n/github-nvim-theme/assets/68758451/4cb59e3d-6ee9-4796-b5bb-e121aa6d95e6)
![Screenshot 2023-05-22 at 12 41 03 PM](https://github.com/projekt0n/github-nvim-theme/assets/68758451/db13a27f-c19c-4958-93a5-0bc91bbfccb8)

**Comment by tmillr** [comment]
Try updating the plugin. A bunch of changes were just merged in #259. It might not be perfect yet, but it should be a substantial improvement:

<img width="779" alt="Screenshot 2023-06-18 at 3 52 34 AM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/9bd93b35-4f48-4799-83c8-6775dc7f90c0">

<img width="778" alt="Screenshot 2023-06-18 at 3 56 37 AM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/dc159f11-ce70-4e1e-b4a4-c1ed4354c589">

<img width="791" alt="Screenshot 2023-06-18 at 3 58 06 AM" src="https://github.com/projekt0n/github-nvim-theme/assets/45028928/4abab38f-6899-4b81-95a7-ea58abd18376">

**Comment by tmillr** [comment]
> Just updated the plugin and tested it out, looks way better than before, there are some wrong colors here and there and as you said it's not perfect yet, but overall it's really good! Really appreciate your work!

Awesome thank you! If there's anything specific left you'd like to report or want checked out, feel free to leave a comment on #252.
