### ISSUE TITLE
FoldColumn has too much contrast to the text & TabLineSel is barely readable because of too little contrast

### ISSUE THREAD

**Issue by wimstefan** [projekt0n/github-nvim-theme#26]
I guess in this case screenshots say more than words ... ;-)

![scrot-2021-07-13-13:33](https://user-images.githubusercontent.com/4605934/125445340-86db766a-f6f2-427e-9d8d-48445f993762.png)
![scrot-2021-07-13-13:32](https://user-images.githubusercontent.com/4605934/125445342-9da662a9-4260-4bfb-8935-192e8acef70e.png)

Swapping foreground & background of FoldColumn gives a nice effect and would be an easy solution.

**Comment by ful1e5** [comment]
We can't change the `folded` colors because this project follows the [primer style](https://primer.style/)(github design system). But I should provide an option to change colors as you wish. I'm attaching a workaround for your problem. Hopefully, This helps you. Also, reference [colors.lua](https://github.com/projekt0n/github-nvim-theme/blob/main/lua/github-theme/colors.lua) file for other colors replacement.

```lua
local themeStyle = "dark"
-- local themeStyle = "dimmed"
-- local themeStyle = "light"
local colors = require("github-theme.colors").setup({themeStyle = themeStyle})

require("github-theme").setup({
  themeStyle = themeStyle,
  colors = {fg_folded = colors.bg_visual_selection, bg_folded = colors.fg},
  -- ... your github-theme config
})

```

check #27 for more information. Thanks for contribution :gift_heart:

**Comment by wimstefan** [comment]
Thank you so much for the quick workaround!

I certainly do not ask you to change the existing colours from the primer style but just to assign different colours to make some elements more visible or appealing. Your suggested workaround is a very good solution!
There is one thing though which I don't understand:
Using 
```lua 
colors = {fg_folded = colors.fg, bg_folded = colors.bg_sidebar}
```
should give me a transparent fold{,column} background if `transparent` is set to `true` if I understand the configuration in [colors.lua](https://github.com/projekt0n/github-nvim-theme/blob/main/lua/github-theme/colors.lua) correctly? It is not the case in [my configuration](https://github.com/wimstefan/dotfiles/blob/master/config/nvim/init.lua#L1086-L1090) ...
Here is the content of nvim_theme.lua
```lua
vim.o.background = 'dark'

if vim.o.background == 'dark' then
  local themeStyle = 'dimmed'
  local colors = require('github-theme.colors').setup({themeStyle = themeStyle})
  require('github-theme').setup({
    colors = {fg_folded = colors.fg, bg_folded = colors.bg_sidebar},
    sidebars = {'netrw', 'packer', 'qf', 'terminal'},
    themeStyle = themeStyle,
    transparent = true,
  })
else
  local themeStyle = 'light'
  local colors = require('github-theme.colors').setup({themeStyle = themeStyle})
  require('github-theme').setup({
    colors = {fg_folded = colors.fg, bg_folded = colors.bg_sidebar},
    sidebars = {'netrw', 'packer', 'qf', 'terminal'},
    themeStyle = themeStyle,
    transparent = true,
  })
end
```
I'm sure I'm doing something wrong but I couldn't find the solution yet ...

**Comment by wimstefan** [comment]
The visibility of `TabLineSel` can be enhanced tremendously by the way if you assign `c.pmenu.select` instead of `c.fg` ...

**Comment by wimstefan** [comment]
Not sure if my comments are still read if the issue is closed ...
Do you want me to open new issues for the two little things I've mentioned above?

**Comment by ful1e5** [comment]
@wimstefan open a new one :+1:
