### ISSUE TITLE
indent-blankline - blue color 

### ISSUE THREAD

**Issue by alitokur** [projekt0n/github-nvim-theme#278]
Affected Version: v0.10.0
Problem
I am currently using NVIM v0.10.0 with the github-nvim-theme color theme and the indent-blankline plugin for indentation. However, I have noticed some unexpected behavior with the theme when used in conjunction with indent-blank line. There are blue lines appearing on my editor, which I believe are related to the interaction between the theme and the plugin.

I have already checked the older issues but its still not working well.

![nvim](https://github.com/projekt0n/github-nvim-theme/assets/20575896/f582371b-5912-4e6e-aaa9-e481a8fee7d5)

**Comment by tmillr** [comment]
Do you know which version of the theme you are using? Maybe try updating the plugin to the latest commit on master/HEAD (or, the latest tag, which is currently `v1.0.0`).
