### ISSUE TITLE
Override colors for tree-sitter highlight groups

### ISSUE THREAD

**Issue by nettrino** [projekt0n/github-nvim-theme#281]
I would want to be able to override the default colors for tree-sitter groups as defined in [treesitter.lua](https://github.com/projekt0n/github-nvim-theme/blob/main/lua/github-theme/group/modules/treesitter.lua). Is there an option to do this somehow?

**Comment by ful1e5** [comment]
@nettrino You can use the `groups` table to override all highlight groups. To override a specific theme variant, create a sub-table with the same name as the colorscheme. Otherwise, use the `all` sub-table.

```lua
require('github-theme').setup({
  -- ...

  groups = {
    -- override for all variants
    all = {
      ['@variable'] = { fg = 'palette.red' },
    },

    -- or override for a specific variant
    -- github_dark = { ... }
  },
})

vim.cmd('colorscheme github_dark')
```
