### ISSUE TITLE
Support for javascript and Golang?

### ISSUE THREAD

**Issue by hkisthebest** [projekt0n/github-nvim-theme#287]
Will there be support for javascript and golang? The current color doesn't look right.

<img width="304" alt="Screenshot 2023-07-27 at 2 01 51 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/31924474/607e6462-e43e-4586-9711-41bda1182432">

Thanks!

**Comment by tmillr** [comment]
Are you using the latest version/release? And are you using treesitter for highlighting?

**Comment by hkisthebest** [comment]
after configuring my treesitter it's all fixed now. thanks
