### ISSUE TITLE
sidebar is not darkened when configured to do so (affects neo-tree, etc.)

### ISSUE THREAD

**Issue by sdemura** [projekt0n/github-nvim-theme#306]
Using neovim 0.9.4, I can't seem to get the 'darkened sidebar' to work.

<img width="984" alt="image" src="https://github.com/projekt0n/github-nvim-theme/assets/11758459/6c5705c7-e624-426b-ae70-ee1799cc83c2">

<img width="984" alt="image" src="https://github.com/projekt0n/github-nvim-theme/assets/11758459/84415354-d9fb-4f0a-b8dc-3ef8affb020c">

I've even tried explicitly setting the sidebars list with:

```lua
  {
    "projekt0n/github-nvim-theme",
    priority = 1000,
    lazy = false,
    config = function()
      require("github-theme").setup({
        options = {
          darken = {
            sidebars = {
              enable = true,
              list = { "neo-tree" },
            },
          },
        },
      })
    end,
  },
```
but no dice.

**Comment by NikoKS** [comment]
Facing the same issue. Currently, I need to manually change the highlight group `NeoTreeNormal`

**Comment by devadathanmb** [comment]
I have the same issue with NvimTree as well

**Comment by tmillr** [comment]
Sorry for the delay. This should be fixed now. Please leave a comment here or open a new issue if you are still experiencing problems after updating your plugin.
