### ISSUE TITLE
Is there any way to set up the background color as transparent?

### ISSUE THREAD

**Issue by sebalfaro** [projekt0n/github-nvim-theme#327]
Hey there, wanted to change the background color of the editor as transparent, something like this, is it possible? 

![image](https://github.com/projekt0n/github-nvim-theme/assets/89085542/e2c221ef-065d-4a7e-b202-e23e44705974)

**Comment by tmillr** [comment]
I am closing this issue as this feature is currently implemented and appears to be working correctly.
