### ISSUE TITLE
`punctuation.delimiter` treesitter group nearly invisible

### ISSUE THREAD

**Issue by jaywonchung** [projekt0n/github-nvim-theme#329]
<img width="561" alt="Screenshot 2024-06-20 at 11 04 15 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/29395896/36010b82-da75-4d51-a56d-f7d7c1f42926">
<img width="560" alt="Screenshot 2024-06-20 at 11 06 28 PM" src="https://github.com/projekt0n/github-nvim-theme/assets/29395896/507d0cce-65a8-45d9-b91e-8e1b384f873a">

Somehow delimiters (e.g., `:`, `;`, `,`, `.`) are nearly invisible. I'm on Neovim 0.10.0 with the latest `github-nvim-theme` commit.

I checked `:hi @punctuation.delimiter` and nothing shows up, so it seems like no highlighting is defined for that group. Am I missing something?

Thanks.

**Comment by tmillr** [comment]
Hi, thanks for reporting this. Which theme are you using?

The issue seems to have to do with the `Delimiter` hl group, which (currently) is supposed to be unhighlighted (and as a result take on the default fg color), but instead it seems that nvim is highlighting it with a default now. So this should be an easy fix.

**Comment by jaywonchung** [comment]
Hey @tmillr, thanks for the response. I'm using `colorscheme github_light`.

**Comment by jaywonchung** [comment]
Ah, I think this is related: https://github.com/neovim/neovim/issues/26378

**Comment by jaywonchung** [comment]
Without knowing what I'm doing, `hi Delimiter guifg=NvimDarkGrey2` fixes the visibility issue at least. Could be a useful workaround until the issue is resolved.

**Comment by tmillr** [comment]
> Without knowing what I'm doing, `hi Delimiter guifg=NvimDarkGrey2` fixes the visibility issue at least. Could be a useful workaround until the issue is resolved.

Yeah that's the hl group causing issues. It's part of nvim's (new?) defaults apparently (see `:h gui-colors`). You can also set `groups.all.Delimiter` to `{}` in the `setup()` call. Running `hi clear Delimiter` after setting the colorscheme with `:colorscheme` also works. Strangely just setting the colorscheme twice also appears to work, although that's probably not an ideal workaround.
