### ISSUE TITLE
Override example throws E5113: attempt to index local 'override' (a nil value)

### ISSUE THREAD

**Issue by craigmac** [projekt0n/github-nvim-theme#340]
Example in docs:

https://github.com/projekt0n/github-nvim-theme/blob/4f44a5c930372c85483d02700f332d34417e50b2/doc/github-nvim-theme.txt#L100

My code:

```lua
require("github-theme").setup({})

local palette = require("github-theme.palette").load("github_dark_default")

local override = require("github-theme").override
override.groups({
  all = {
    WinSeparator = { fg = palette.gray },
  },
})

vim.cmd.colorscheme("github_dark_default")
```

**Comment by tmillr** [comment]
I think this is either outdated or a typo, it's supposed to be `local override = require("github-theme.override")`. But you're probably better off just putting the overrides directly into the setup call as [shown here](https://github.com/projekt0n/github-nvim-theme?tab=readme-ov-file#customize-palettes-and-groups).

**Comment by craigmac** [comment]
I've tried that as well, after checking the source, it also doesn't work.

**Comment by tmillr** [comment]
Change `palette.gray` to `palette.gray.base` or `palette.gray.bright`.

**Comment by tmillr** [comment]
hmmmm the example doesn't work for me either, but using `setup()` it does:

```lua
local palette = require('github-theme.palette').load('github_dark_default')

require('github-theme').setup({
  groups = { all = { WinSeparator = { fg = palette.gray.base } } },
})

vim.cmd.colorscheme('github_dark_default')
```

Also make sure you are on the latest commit or release. You may also want to try removing the cache dir (or, run `:GithubThemeCompile`).

**Comment by tmillr** [comment]
This should be fixed now and the docs have been updated.
