### ISSUE TITLE
Cannot override background color

### ISSUE THREAD

**Issue by l-lin** [projekt0n/github-nvim-theme#359]
Hello,

I have the following configuration:

```lua
require("github-theme").setup({
  specs = {
    github_light_high_contrast = {
      bg0 = "#EFF1F5",
      bg1 = "#EFF1F5",
    },
  },
})
```

Since https://github.com/projekt0n/github-nvim-theme/pull/328, the background color is not overriden and stays in pure white `#FFFFFF`.

I'm not sure if there were a breaking change in the configuration?

I did run `:GithubThemeCompile`, but no change :(

**Comment by tmillr** [comment]
Thanks for reporting this. I will look into it.
