### ISSUE TITLE
Assigning `bg_sidebar` to `bg_folded` doesn't make the folds{,column} transparent with transparency enabled

### ISSUE THREAD

**Issue by wimstefan** [projekt0n/github-nvim-theme#36]
I'm assigning different colors to folds as you suggested in [issue #26](https://github.com/projekt0n/github-nvim-theme/issues/26#issuecomment-879748048) and it works so well :)

There is one thing though which I don't understand:
Using 
```lua 
colors = {fg_folded = colors.fg, bg_folded = colors.bg_sidebar}
```
should give me a transparent fold{,column} background if `transparent` is set to `true` if I understand the configuration in [colors.lua](https://github.com/projekt0n/github-nvim-theme/blob/main/lua/github-theme/colors.lua) correctly? It is not the case in [my configuration](https://github.com/wimstefan/dotfiles/blob/master/config/nvim/init.lua#L1086-L1090) ...
Here is the content of nvim_theme.lua
```lua
vim.o.background = 'dark'

if vim.o.background == 'dark' then
  local themeStyle = 'dimmed'
  local colors = require('github-theme.colors').setup({themeStyle = themeStyle})
  require('github-theme').setup({
    colors = {fg_folded = colors.fg, bg_folded = colors.bg_sidebar},
    sidebars = {'netrw', 'packer', 'qf', 'terminal'},
    themeStyle = themeStyle,
    transparent = true,
  })
else
  local themeStyle = 'light'
  local colors = require('github-theme.colors').setup({themeStyle = themeStyle})
  require('github-theme').setup({
    colors = {fg_folded = colors.fg, bg_folded = colors.bg_sidebar},
    sidebars = {'netrw', 'packer', 'qf', 'terminal'},
    themeStyle = themeStyle,
    transparent = true,
  })
end
```
I'm sure I'm doing something wrong but I couldn't find the solution yet ...

**Comment by ful1e5** [comment]
I patched 6a95cca to the upstream. Now you are able to set transparent background with `NONE` value.

```lua
vim.o.background = "dark"
local transparent = true

if vim.o.background == "dark" then
  local themeStyle = "dimmed"
  local colors = require("github-theme.colors").setup({themeStyle = themeStyle})
  require("github-theme").setup({
    colors = {bg_folded = transparent and "NONE" or colors.bg_sidebar},
    sidebars = {"netrw", "packer", "qf", "terminal"},
    themeStyle = themeStyle,
    transparent = transparent
  })
else
  local themeStyle = "light"
  local colors = require("github-theme.colors").setup({themeStyle = themeStyle})
  require("github-theme").setup({
    colors = {bg_folded = transparent and "NONE" or colors.bg_sidebar},
    sidebars = {"netrw", "packer", "qf", "terminal"},
    themeStyle = themeStyle,
    transparent = transparent
  })
end
```

**Comment by ful1e5** [comment]
Also, You don't have to override the `fg_folded` value to `colors.fg` because it's already assigned inside [colors.lua](https://github.com/projekt0n/github-nvim-theme/blob/main/lua/github-theme/colors.lua).

https://github.com/projekt0n/github-nvim-theme/blob/03d4e5f5946b7790e0ef7314f25db670404c4add/lua/github-theme/colors.lua#L121-L123

**Comment by wimstefan** [comment]
Looking good. Very good :D 
I guess I simply was thinking the wrong way when I supposed that `bg_sidebar` is getting transparent as well just when I've set `transparent = true` ;)

Thank you so much for your support! 🙏
