### ISSUE TITLE
JSX/TSX tags are missing highlights with nvim 0.10

### ISSUE THREAD

**Issue by anthonyshew** [projekt0n/github-nvim-theme#360]
Just got done upgrading to nvim 0.10, went to write some code, and realized I lost the green color of JSX components when using `github-dark-default`.

Before (nvim 0.9, VSCode):
> This is my VSCode. I just got done upgrading nvim and don't want to touch it for a moment. 😬  
> With nvim 0.9, those tokens were the same green.
![CleanShot 2024-08-05 at 16 14 28@2x](https://github.com/user-attachments/assets/359e4f21-ad78-482a-8650-654eac8db27a)

After (nvim 0.10):
![CleanShot 2024-08-05 at 16 10 34@2x](https://github.com/user-attachments/assets/530a0b59-8ff6-4eb4-9596-3668d6a22dda)

Trying to see if I can sort it out myself but figuring the experts maintaining this will be more savvy than I will. 😄

**Comment by tmillr** [comment]
Thank you for reporting this and bringing it to our attention! This should be fixed now. Please let us know if you experience any more problems (you may respond here with a comment, or open a new issue if it is unrelated to this one).

**Comment by anthonyshew** [comment]
Much better! I don't know if this was intentional, but custom components are now gold, a different color than the HTML elements. I seem to remember they were the same green before, but I may be wrong. I do notice they are the same green in VSCode, though.

![CleanShot 2024-09-02 at 22 08 48@2x](https://github.com/user-attachments/assets/2397e181-58f7-4a48-a2ac-c5f62ee2974b)

And apologies for taking so long to report back! Missed it in my GitHub notifications and only just now noticed that things were back to normal. Much appreciated!
