### ISSUE TITLE
Error - "Invalid node type 'jsx_opening_element'" since last update

### ISSUE THREAD

**Issue by nilssonr** [projekt0n/github-nvim-theme#361]
Hey, just updated to the latest version of this repository and immediately ran into an issue with my Angular project in Typescript. I have not tested if the theme breaks with any non-angular Typescript code.  

<img width="1479" alt="Screenshot 2024-08-07 at 00 19 14" src="https://github.com/user-attachments/assets/35c13947-23ae-473a-a0d9-5e4e385cf484">

Please let me know what else I would need to provide in order to help troubleshoot this. And thanks for a great theme! 

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

Reverting to the previous commit works great: 

<img width="706" alt="Screenshot 2024-08-07 at 00 26 17" src="https://github.com/user-attachments/assets/f4250690-57dc-4066-8349-456b6af6e27e">

**Comment by AzashiroMerume** [comment]
i was thinking it is typescript parser issue))

**Comment by tmillr** [comment]
Thank you, I'll look into this. I think it might be an error that only occurs with typescript (while jsx, tsx, and js are ok). I overlooked the fact that even though this node is used for jsx, tsx, and js, it is not used for ts for some reason lol. Unfortunately this is one of the few things left that our CI tests don't cover yet (which hopefully we can change soon).

**Comment by tmillr** [comment]
Thank you for reporting this and bringing it to our attention! This should be fixed now. Please let us know if you experience any more problems (you may respond here with a comment, or open a new issue if it is unrelated to this one).
