### ISSUE TITLE
Incorrect highlight of name/binding in python import statements

### ISSUE THREAD

**Issue by elvisbejko** [projekt0n/github-nvim-theme#371]
The `treesitter` highlight doesn't integrate  well with `python`. 

I get the imports all highlighted with the same color (reddish):
![{D0018636-4D9B-4C76-ADA6-B557F79CB54F}](https://github.com/user-attachments/assets/a1446c6f-85eb-443c-ae03-2164f16f8182)

Looking at similar code here on github, the expected look should be something like:
![{725D1309-B267-48F6-8B9F-CEF73ED19C5A}](https://github.com/user-attachments/assets/225c3149-8bd1-4635-acfc-fb0790001da2)

My github-nvim-theme configuration .lua and treesitter.lua follow:
`treesitter.lua`
```lua
return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local config = require("nvim-treesitter.configs")
		config.setup({
			auto_install = true,
			ensure_installed = { "lua", "c", "python", "rust", "latex" },
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
```
`github-nvim-theme.lua`

```lua
return {
	"projekt0n/github-nvim-theme",
	lazy = false,
	priority = 1000,
	config = function()
		require("github-theme").setup({
			groups = {
				all = {
					Normal = { bg = "NONE" },
					NormalNC = { bg = "NONE" },
					NetrwTreeBar = { bg = "NONE" }, -- Transparent background for netrw sidebar
					NetrwDir = { bg = "NONE" }, -- Transparent background for directories in netrw
					ColorColumn = { bg = "#1d1d1d" },
				},
			},
		})
		vim.cmd("colorscheme github_dark")
		vim.o.cursorline = true
		vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#FFF9D6", bold = true })
		vim.cmd("hi clear cursorline")
	end,
}

```
Since I recently bumped to a higher `nvim` version, I checked with earlier versions <0.10.x & the issue still persists. 
Removing the highlight from `treesitter.lua` reverts the style to something too simplistic.

**Comment by tmillr** [comment]
I'm not observing such behavior on my end.

<img width="283" alt="Screenshot 2024-12-24 at 10 05 12 PM" src="https://github.com/user-attachments/assets/b1339856-6d14-48d2-82ae-742651af4039" />


Perhaps there is an issue with your treesitter setup/config?

Put the cursor over `io` and run the vim command `:Inspect`. What does it say?

**Comment by elvisbejko** [comment]
@tmillr  Thanks for taking the time:
* plugin up-to-date
* `:Inspect` on `io` gives me
![{653C6466-423E-491B-BBB6-F2D05A555FA1}](https://github.com/user-attachments/assets/04449bc8-899f-41d3-b2a6-9599b3eb8fff)

**Comment by tmillr** [comment]
Ok, I think I found the cause of the issue: https://github.com/nvim-treesitter/nvim-treesitter/pull/7378
