### ISSUE TITLE
Lualine theme hides status line in Session's window until focused

### ISSUE THREAD

**Issue by mixedCase** [projekt0n/github-nvim-theme#38]
After saving with `:mksession` with 4 windows tiled and opening it back up with `nvim -S`, every non-focused window looks as if I had enabled `hideInactiveStatusline`, but I haven't. Once I focus each window, its respective statusline becomes visible.

**Comment by ful1e5** [comment]
It's happening without a `github` theme. I'm thinking it might be a `lualine` bug :thinking: 

https://user-images.githubusercontent.com/24286590/126063072-9db04682-50c8-4cfd-b3b2-c87b433861e4.mp4

**Comment by ful1e5** [comment]
Tack the issue @ hoob3rt/lualine.nvim#309
