### ISSUE TITLE
doesn't look like syntax theme is applying?

### ISSUE THREAD

**Issue by mrjones2014** [projekt0n/github-nvim-theme#53]
Hi, great theme. Looks amazing.

However it doesn't look like it's applying the theme to the syntax. I'm using `vim-polyglot` but I've tried removing/disabling that and there is no change.

![image](https://user-images.githubusercontent.com/8648891/127887797-ee771d99-92a7-49a1-810c-75b9adee2db5.png)

my theme is configured as follows:
```
local g = vim.g
local api = vim.api

vim.opt.termguicolors = true
vim.opt.syntax = 'on'

require('github-theme').setup({
  themeStyle = 'dark',
  sidebars = {'packer', 'NvimTree', 'term', 'terminal'},
})

vim.cmd([[
  filetype plugin on
  colorscheme github
  highlight TrailingWhitespace ctermbg=red guibg=red
  match TrailingWhitespace /\s\+$/
]])
```

**Comment by chuckmasucci** [comment]
Are you using TreeSitter, and have Typescript installed? I had to `TSInstall typescript` to make it work on my end.

**Comment by mrjones2014** [comment]
Ah okay I didn’t realize I needed tree sitter for it to work.
