### ISSUE TITLE
Error "E492: Not an editor command" in config file

### ISSUE THREAD

**Issue by GRcrafter** [projekt0n/github-nvim-theme#55]
Hey, I'm trying to use the dimmed theme on nvim 0.4.4, but when I am ready to use it (init.vim setup) my config file throws the error said in the title:
![image](https://user-images.githubusercontent.com/82709728/128611785-6324f427-47d8-4607-9ec6-eb5e60f054f7.png)
This is my config file, copied from the readme
![image](https://user-images.githubusercontent.com/82709728/128611807-bf7ec861-f72c-42c1-a9f7-06c589110f70.png)
Any help would be greatly appreciated

**Comment by ful1e5** [comment]
try with `nvim 0.5`

**Comment by GRcrafter** [comment]
Thanks, it works perfectly now
