### ISSUE TITLE
Why is my colorscheme not looking like the screenshots?

### ISSUE THREAD

**Issue by vzytoi** [projekt0n/github-nvim-theme#63]
Hey, I just installed this colorscheme, which looks really good but It don't looks the same when I installed it. Here is my config.
```
    use {
        'projekt0n/github-nvim-theme',
        config = function()
            require("github-theme").setup({
              themeStyle = "dark",
            })
        end
    }
```
```
vim.o.termguicolors = true
vim.o.background = 'dark'
```

![colorschemenotlookingok](https://user-images.githubusercontent.com/65293868/131030159-5fa07b38-69b4-4f5f-bcff-aacbf8aae498.PNG)

**Comment by ful1e5** [comment]
check #16 for progress
