### ISSUE TITLE
transparent + hideEndOfBuffer still shows EndOfBuffer symbols

### ISSUE THREAD

**Issue by jakobkhansen** [projekt0n/github-nvim-theme#66]
When both transparent and hideEndOfBuffer is true, EndOfBuffer symbols (~) still seems to show, this seems like a bug.

**Comment by ful1e5** [comment]
There is no such thing as hidden `EndOfBuffer` in nvim. This colorscheme basically set `EndOfBuffer` color with the background color. Means it's still there but we can't see.

I removed a bit of code for setting the `EndOfBuffer` color. Now, It still appears but it is now less interrupting. You can also override the value of the colors with `eob` & `sidebar_eob` :

```lua
require("github-theme").setup({
  colors = {sidebar_eob = "", eob = ""}
  -- other config
})
```
