### ISSUE TITLE
How to change the search highlight color

### ISSUE THREAD

**Issue by zer09** [projekt0n/github-nvim-theme#77]
Hello good day,

Previously I'm using base16-vim colortheme, and using the search highlight color of `#dae84d`.

How I can change the search highlight color to `#dae84d`?

Thanks

**Comment by ful1e5** [comment]
```lua
require("github-theme").setup({
  colors = {bg_search = "#dae84d", fg_search = "#000000"}
})
```

check [README.md#configuration](https://github.com/projekt0n/github-nvim-theme#configuration) for other configuration.

**Comment by zer09** [comment]
@ful1e5 

I tried this 
```vim
let g:github_colors = [bg_search = "#dae84d", error = "#000000"]
colorscheme github_dark_default
```
But I got  `E121: Undefined variable: bg_search`

The same with the readme example
```vim
" Change the "hint" color to the "orange" color, and make the "error" color bright red
let g:github_colors = [hint = "orange", error = "#ff0000"]
```
This will error to `E121: Undefined variable: hint`

**Comment by ful1e5** [comment]
There are some bugs in this theme regarding `.vim` config support. So, stick with `lua` until I manage to fix it.

```lua
vim.g.github_colors = {bg_search = "#dae84d", fg_search = "#000000"}
vim.cmd [[ colorscheme github_dark_default]]
```

**Comment by ful1e5** [comment]
Also, You have to wrap this :point_up_2:  config with ```lua << EOF ... EOF``` for `.vim` config.

```vim
lua << EOF
vim.g.github_colors = {bg_search = "#dae84d", fg_search = "#000000"}
vim.cmd [[ colorscheme github_dark_default]]
EOF
```

**Comment by ful1e5** [comment]
Here is the `vim` workaround. Also updated the docs :slightly_smiling_face: 
```vim
let g:github_colors = {
  \ 'error': '#dae84d',
  \ 'fg_search': '#000000'
\ }

colorscheme github_dark_default
```
