### ISSUE TITLE
Support iTerm

### ISSUE THREAD

**Issue by yamatsum** [projekt0n/github-nvim-theme#8]
Are you planning to support iTerm?

**Comment by st3fan** [comment]
If this just needs true color support then this should be fine in iTerm?

Taken from https://emacs.stackexchange.com/q/32506/153

```
$ cat terminfo-24bit.src

# Use colon separators.
xterm-24bit|xterm with 24-bit direct color mode,
   use=xterm-256color,
   setb24=\E[48:2:%p1%@{65536@}%/%d:%p1%@{256@}%/%@{255@}%&%d:%p1%@{255@}%&%dm,
   setf24=\E[38:2:%p1%@{65536@}%/%d:%p1%@{256@}%/%@{255@}%&%d:%p1%@{255@}%&%dm,
# Use semicolon separators.
xterm-24bits|xterm with 24-bit direct color mode,
   use=xterm-256color,
   setb24=\E[48;2;%p1%@{65536@}%/%d;%p1%@{256@}%/%@{255@}%&%d;%p1%@{255@}%&%dm,
   setf24=\E[38;2;%p1%@{65536@}%/%d;%p1%@{256@}%/%@{255@}%&%d;%p1%@{255@}%&%dm,

$ tic -x -o ~/.terminfo terminfo-24bit.src

TERM=xterm-24bit emacs -nw
```

Run `nvim` instead of `emacs` obviously :-)

**Comment by yamatsum** [comment]
It's not an iTerm support from neovim. And like kitty, it's a color theme support for the iTerm.

**Comment by st3fan** [comment]
Oh apologies. I misunderstood. I agree, an iTerm2 color theme would be wonderful to have.

**Comment by shaunsingh** [comment]
You can find themes for GitHub and GitHub dark here: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/a42fb6b1ce66f3effd5a9e7ede4a39d5c122a3af/README.md

**Comment by lfilho** [comment]
Hey I found this issue but it seems we don't support iTerm anymore, is that correct? I would love an iTerm theme :)

**Comment by lfilho** [comment]
@tmillr yes! That was exactly what i was after and couldn't find! Thank you!! I'll make a PR to the main readme so others can find it more easily too
