### ISSUE TITLE
inactive statusline same color as background

### ISSUE THREAD

**Issue by sdemura** [projekt0n/github-nvim-theme#83]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/11758459/134241224-7a3b0fbd-0e1f-471a-947f-411d79ebf131.png">

Not sure which change it was that was merged late last night/this morning, but inactive statusline's have the same color as the background, making it very hard to tell what's going on.

**Comment by ful1e5** [comment]
Can you able share your config?

**Comment by sdemura** [comment]
Hi. Here's the relevant lualine/github nvim theme config
```
lua <<EOF
-- Github Dark Theme
require('lualine').setup{
    options = {theme = 'github'},
    extensions = {'fugitive', 'nvim-tree'},
    sections = {
      lualine_a = {'mode'},
      lualine_b = {'branch'},
      lualine_c = {{'filename', file_status = true, path=1}},
      lualine_x = {'encoding', 'fileformat', 'filetype'},
      lualine_y = {'progress'},
      lualine_z = {'location'}
    },
    inactive_sections = {
      lualine_a = {},
      lualine_b = {},
      lualine_c = {'filename'},
      lualine_x = {'location'},
      lualine_y = {},
      lualine_z = {}
    }
}
require('github-theme').setup({theme_style = 'dark'}) 
```

**Comment by ful1e5** [comment]
I Can't able reproduce this issue on `NVIM v0.6.0-dev+318-g21f755527`. I'm guessing you should try it on neovim-nightly.

**Comment by sdemura** [comment]
Yea... I'm on neovim 0.5...

**Comment by sdemura** [comment]
Reproducible on latest nightly... `v0.6.0-dev+aba397991`

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/11758459/134515596-ae9c4a81-7f54-454c-a39f-572b7b4420d1.png">

**Comment by craigmac** [comment]
This issue still persists without Lualine, it is setting StatuslineNC to same colour as background when using light mode.
