### ISSUE TITLE
How can I change the color of functions?

### ISSUE THREAD

**Issue by jrafaaael** [projekt0n/github-nvim-theme#85]

**Comment by ful1e5** [comment]
```lua
require("github-theme").setup({
  colors = {syntax = {func = "#fff000"}} -- yellow color for function name & function call
  -- ... other config
})
```
reference [colors.lua](https://github.com/projekt0n/github-nvim-theme/blob/4bc66fa3deaf44cd32f33531139829ab31192c77/lua/github-theme/colors.lua#L18-L573) for other colors override.

**Comment by jrafaaael** [comment]
Thank you!

**Comment by kiryph** [comment]
@ful1e5 

I get an error for
```lua
require("github-theme").setup({
  colors = { syntax = { string = "orange"} },
})
```
```
github-theme/util.lua:208: color "string" does not exist
```

Full error:
```
|| Error detected while processing /Users/kiryph/.config/nvim/init.lua:
|| E5113: Error while calling lua chunk: ...packer/start/github-nvim-theme/lua/github-theme/util.lua:208: color "string" does not exist
|| stack traceback:
|| 	[C]: in function 'error'
|| 	...packer/start/github-nvim-theme/lua/github-theme/util.lua:208: in function 'color_overrides'
|| 	...packer/start/github-nvim-theme/lua/github-theme/util.lua:197: in function 'color_overrides'
|| 	...cker/start/github-nvim-theme/lua/github-theme/colors.lua:31: in function 'setup'
|| 	...acker/start/github-nvim-theme/lua/github-theme/theme.lua:14: in function 'setup'
|| 	...packer/start/github-nvim-theme/lua/github-theme/init.lua:15: in function 'setup'
|| 	/Users/kiryph/.config/nvim/init.lua:472: in main chunk
```
What do I miss?

**Comment by ful1e5** [comment]
It seems that the `color_override` utility function seems to be broken. We'd like to fix it, but We're refactoring the whole theme. So, the effort is futile. Apart from that, you can achieve the same thing in another way, by the overriding highlight. For that, you need to have `dev` mode enabled; Maybe if the highlight is not defined in the theme.

You can use `source $VIMRUNTIME/syntax/hitest.vim` or `:Telescope highlights` to view all highlights and also reference [colors.lua](https://github.com/projekt0n/github-nvim-theme/blob/4bc66fa3deaf44cd32f33531139829ab31192c77/lua/github-theme/colors.lua#L18-L573) for accessing colors with `c.*`.

```lua
require('github-theme').setup({
  -- ...
  overrides = function(c)
    return {
      String = { fg = c.orange },
    }
  end,
  dev = true,
})
```
