### ISSUE TITLE
[question] How to automatically switch themes?

### ISSUE THREAD

**Issue by MaxVerevkin** [projekt0n/github-nvim-theme#9]
For `kitty`, I have this in my config:
```
allow_remote_control yes
include ./theme.conf
```
and I use a custom script (https://github.com/MaxVerevkin/day-night) that automatically "symlinks" `theme.conf` to an appropriate theme based on the time of day. To apply the theme to all terminals "on the fly", this script also runs `kitty @ set-colors --all --configured ~/.config/kitty/theme.conf`.

My question is - can I do something similar with `neovim`? Perhaps this is a wrong place to ask, but anyway.

**Comment by ful1e5** [comment]
No. I'm not doing any symlink stuff inside my kitty config. 

As far as I know, kitty doesn't support any hot-reloading. Where we talk about `make` commands though, it's rewriting the appropriate themes to the config(themes/github.conf) file. That's why I wrote individual make commands for the appropriate theme style. [Here](https://github.com/ful1e5/dotfiles/tree/main/kitty/.config/kitty) is my kitty config hopefully this helps you.

**Comment by kristijanhusak** [comment]
@MaxVerevkin Try this: https://gist.github.com/kristijanhusak/2039c3cca4a574c5521e39b4d0c5ce66

**Comment by MaxVerevkin** [comment]
@kristijanhusak Thanks, I haven't tried it yet, but it looks like in order to apply nvim theme I'll have to reopen it. Am I wrong?

**Comment by kristijanhusak** [comment]
@MaxVerevkin yeah, it's triggered from the terminal. You could maybe extend the script to do something additionally if you run it from neovim, but I haven't tried anything like that.

**Comment by MaxVerevkin** [comment]
I think I've figured that out (at least it 'works for me')

```lua
-- Set colorscheme
vim.o.termguicolors = true
set_colors = function()
    require("github-theme").setup{ themeStyle = vim.o.background }
end
set_colors()
require'timer'.add(
    function()
        local daynight = io.popen("day-night --lat XX --lon XX --interval 0"):read()
        if daynight == "day" then
            if vim.o.background ~= "light" then
                vim.o.background = "light"
                set_colors()
            end
        else
            if vim.o.background ~= "dark" then
                vim.o.background = "dark"
                set_colors()
            end
        end
        return 5 * 1000
    end
)
```

Where `timer` is https://github.com/alex-popov-tech/timer.nvim and `day-night` is https://github.com/MaxVerevkin/day-night
