### ISSUE TITLE
line number color has changed recently, only for transparent background

### ISSUE THREAD

**Issue by meinside** [projekt0n/github-nvim-theme#93]
Hi,

I see the color of line numbers has changed from gray to white, especially in transparent background.

It seems okay in non-transparent configuration.

Here are my screenshots and their mimimal init.lua file contents:

<img width="656" alt="init_lua" src="https://user-images.githubusercontent.com/185988/134834684-b7f46b9d-5f01-4ebd-b791-878394cf6d17.png">

It was gray back in v0.0.2 like this:

<img width="655" alt="init_lua_v002" src="https://user-images.githubusercontent.com/185988/134834725-128af126-4e5b-4f58-83d7-1addc5f1092a.png">

Is this intentional, or is there anything I missed?

**Comment by ful1e5** [comment]
check 5528f3c
