### ISSUE TITLE
Support colors for buffers and tabs component in lualine

### ISSUE THREAD

**Issue by kdheepak** [projekt0n/github-nvim-theme#97]
In @shadmansaleh's fork of lualine.nvim: https://github.com/shadmansaleh/lualine.nvim

There is support for buffer and tab line (https://github.com/shadmansaleh/lualine.nvim/pull/42). However with this theme both active and inactive buffers and tabs have the same background color. It ends up looking like this:

![](https://user-images.githubusercontent.com/1813121/133931342-d17ad45c-03c6-494b-8e58-6de5035f4b9d.png)

There's no separators between the active buffers and inactive buffers (i.e. between `buffers.lua` and `tabs.lua`).

This is what users would expect it to look like:

![](https://user-images.githubusercontent.com/1813121/133932516-317c2ab8-ecca-4ec5-aaea-931491b7ef8a.png)

Here's what is looks like in another theme:

![](https://user-images.githubusercontent.com/13149513/133934883-fff6b20d-da7e-48b0-8ec0-bed47d12a35d.png)

**Comment by ful1e5** [comment]
I like to receive PR for this enhancement.
