### ISSUE TITLE
Error: Config themeStyle does not exist

### ISSUE THREAD

**Issue by budoteam** [projekt0n/github-nvim-theme#99]
Hi

When I try to run Neovim with this Github-Theme in macOS (iTerm2), I get the following Error:

```
Error detected while processing /Users/fabian/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...cker/start/github-nvim-theme/lua/github-theme/config.lua:47: projekt0n/github-nvim-theme: Config themeStyle does not exist
```

No Problems with the same config on Linux. Does anyone know, why this happens?

best regards 
Fabian

**Comment by ful1e5** [comment]
`themeStyle` config is now **snake_case** means `theme_style`. 
check the updated docs [here](https://github.com/projekt0n/github-nvim-theme#configuration).

**ref**:  f307dfd
